/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // docs: [
  //   {
  //     type: 'category',
  //     label: '操作系统相关',
  //     collapsed: false,
  //     items: [
  //       'os-info/centos/centos',
  //       'os-info/centos/ubuntu',
  //       'os-info/docker/docker',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '应用程序运维相关',
  //     collapsed: false,
  //     items: [
  //       'app-info/git/git',
  //       'app-info/nginx/nginx',
  //       {
  //         type: 'category',
  //         label: 'java系列',
  //         collapsed: false,
  //         items: [
  //           'app-info/a-java/a-java',
  //           'app-info/a-java/ruoyi',
  //           'app-info/a-java/ruoyifontend',
  //         ],
  //       },
  //       'app-info/maven/maven',
  //       'app-info/mysql/mysql',
  //     ],
  //   },
  //
  //   {
  //     type: 'category',
  //     label: 'IDE配置相关',
  //     collapsed: false,
  //     items: [
  //       'ide-info/webstorm/webstorm',
  //       'ide-info/docusaurus/docusaurus',
  //     ],
  //   },
  // ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
